//////////////////////////////////////////////////////////
// This class has been automatically generated on
// Fri Mar 21 16:49:25 2014 by ROOT version 5.32/00
// from TTree photon/v1
// found on file: /mnt/hadoop/cms/store/user/dgulhan/HIMC/Jet80/Track8_Jet21_STARTHI53_LV1/merged3/HiForest_Pythia_Hydjet_Jet80_Track8_Jet21_STARTHI53_LV1_merged_forest_0.root
//////////////////////////////////////////////////////////
#include "commonSetup.h"
#include <iostream>
#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <TTree.h>
#include <TBranch.h>

class Photons {
public :
   Photons(){};
   ~Photons(){};

   // Declaration of leaf types
   Int_t           run;
   Int_t           event;
   Int_t           bunchCrossing;
   Int_t           luminosityBlock;
   Int_t           nPhotons;
   Float_t         pt[82];   //[nPhotons]
   Float_t         energy[82];   //[nPhotons]
   Float_t         rawEnergy[82];   //[nPhotons]
   Float_t         eta[82];   //[nPhotons]
   Float_t         phi[82];   //[nPhotons]
   Float_t         r9[82];   //[nPhotons]
   Bool_t          isEB[82];   //[nPhotons]
   Bool_t          isEBGap[82];   //[nPhotons]
   Bool_t          isEEGap[82];   //[nPhotons]
   Bool_t          isEBEEGap[82];   //[nPhotons]
   Bool_t          isTransGap[82];   //[nPhotons]
   Float_t         preshowerEnergy[82];   //[nPhotons]
   Float_t         numOfPreshClusters[82];   //[nPhotons]
   Float_t         ESRatio[82];   //[nPhotons]
   Float_t         clustersSize[82];   //[nPhotons]
   Float_t         scSize[82];   //[nPhotons]
   Float_t         phiWidth[82];   //[nPhotons]
   Float_t         etaWidth[82];   //[nPhotons]
   Float_t         scEta[82];   //[nPhotons]
   Float_t         scPhi[82];   //[nPhotons]
   Float_t         sigmaEtaEta[82];   //[nPhotons]
   Float_t         sigmaIetaIeta[82];   //[nPhotons]
   Float_t         sigmaIphiIphi[82];   //[nPhotons]
   Float_t         sieie50[82];   //[nPhotons]
   Float_t         sieie45[82];   //[nPhotons]
   Float_t         sieie47[82];   //[nPhotons]
   Float_t         sieie42[82];   //[nPhotons]
   Float_t         sieie39[82];   //[nPhotons]
   Float_t         covPhiPhi[82];   //[nPhotons]
   Float_t         covEtaPhi[82];   //[nPhotons]
   Float_t         covEtaEta[82];   //[nPhotons]
   Float_t         r1x5[82];   //[nPhotons]
   Float_t         r2x5[82];   //[nPhotons]
   Float_t         e1x5[82];   //[nPhotons]
   Float_t         e2x5[82];   //[nPhotons]
   Float_t         eMax[82];   //[nPhotons]
   Float_t         e2nd[82];   //[nPhotons]
   Float_t         e2x2[82];   //[nPhotons]
   Float_t         e3x3[82];   //[nPhotons]
   Float_t         e3x2[82];   //[nPhotons]
   Float_t         e4x4[82];   //[nPhotons]
   Float_t         e5x5[82];   //[nPhotons]
   Float_t         e2overe8[82];   //[nPhotons]
   Float_t         eRight[82];   //[nPhotons]
   Float_t         eLeft[82];   //[nPhotons]
   Float_t         eTop[82];   //[nPhotons]
   Float_t         eBottom[82];   //[nPhotons]
   Float_t         e2x5Right[82];   //[nPhotons]
   Float_t         e2x5Left[82];   //[nPhotons]
   Float_t         e2x5Top[82];   //[nPhotons]
   Float_t         e2x5Bottom[82];   //[nPhotons]
   Float_t         seedTime[82];   //[nPhotons]
   Float_t         seedChi2[82];   //[nPhotons]
   Float_t         seedOutOfTimeChi2[82];   //[nPhotons]
   Float_t         seedRecoFlag[82];   //[nPhotons]
   Float_t         seedSeverity[82];   //[nPhotons]
   Float_t         swissCrx[82];   //[nPhotons]
   Float_t         hadronicOverEm[82];   //[nPhotons]
   Float_t         hadronicDepth1OverEm[82];   //[nPhotons]
   Float_t         hadronicDepth2OverEm[82];   //[nPhotons]
   Float_t         ecalRecHitSumEtConeDR04[82];   //[nPhotons]
   Float_t         hcalTowerSumEtConeDR04[82];   //[nPhotons]
   Float_t         hcalDepth1TowerSumEtConeDR04[82];   //[nPhotons]
   Float_t         hcalDepth2TowerSumEtConeDR04[82];   //[nPhotons]
   Float_t         trkSumPtHollowConeDR04[82];   //[nPhotons]
   Float_t         trkSumPtSolidConeDR04[82];   //[nPhotons]
   Float_t         ecalRecHitSumEtConeDR03[82];   //[nPhotons]
   Float_t         hcalTowerSumEtConeDR03[82];   //[nPhotons]
   Float_t         hcalDepth1TowerSumEtConeDR03[82];   //[nPhotons]
   Float_t         hcalDepth2TowerSumEtConeDR03[82];   //[nPhotons]
   Float_t         trkSumPtHollowConeDR03[82];   //[nPhotons]
   Float_t         trkSumPtSolidConeDR03[82];   //[nPhotons]
   Int_t           isEle[82];   //[nPhotons]
   Int_t           hasPixelSeed[82];   //[nPhotons]
   Float_t         detaEle[82];   //[nPhotons]
   Float_t         dphiEle[82];   //[nPhotons]
   Float_t         eleCharge[82];   //[nPhotons]
   Float_t         eleEoverP[82];   //[nPhotons]
   Float_t         c1[82];   //[nPhotons]
   Float_t         c2[82];   //[nPhotons]
   Float_t         c3[82];   //[nPhotons]
   Float_t         c4[82];   //[nPhotons]
   Float_t         c5[82];   //[nPhotons]
   Float_t         r1[82];   //[nPhotons]
   Float_t         r2[82];   //[nPhotons]
   Float_t         r3[82];   //[nPhotons]
   Float_t         r4[82];   //[nPhotons]
   Float_t         r5[82];   //[nPhotons]
   Float_t         t1[82];   //[nPhotons]
   Float_t         t2[82];   //[nPhotons]
   Float_t         t3[82];   //[nPhotons]
   Float_t         t4[82];   //[nPhotons]
   Float_t         t5[82];   //[nPhotons]
   Float_t         t1PtCut[82];   //[nPhotons]
   Float_t         t2PtCut[82];   //[nPhotons]
   Float_t         t3PtCut[82];   //[nPhotons]
   Float_t         t4PtCut[82];   //[nPhotons]
   Float_t         t5PtCut[82];   //[nPhotons]
   Float_t         cc1[82];   //[nPhotons]
   Float_t         cc2[82];   //[nPhotons]
   Float_t         cc3[82];   //[nPhotons]
   Float_t         cc4[82];   //[nPhotons]
   Float_t         cc4j[82];   //[nPhotons]
   Float_t         cc5[82];   //[nPhotons]
   Float_t         cc05[82];   //[nPhotons]
   Float_t         cr1[82];   //[nPhotons]
   Float_t         cr2[82];   //[nPhotons]
   Float_t         cr3[82];   //[nPhotons]
   Float_t         cr4[82];   //[nPhotons]
   Float_t         cr5[82];   //[nPhotons]
   Float_t         cr4j[82];   //[nPhotons]
   Float_t         ct1[82];   //[nPhotons]
   Float_t         ct2[82];   //[nPhotons]
   Float_t         ct3[82];   //[nPhotons]
   Float_t         ct4[82];   //[nPhotons]
   Float_t         ct5[82];   //[nPhotons]
   Float_t         ct1PtCut20[82];   //[nPhotons]
   Float_t         ct2PtCut20[82];   //[nPhotons]
   Float_t         ct3PtCut20[82];   //[nPhotons]
   Float_t         ct4PtCut20[82];   //[nPhotons]
   Float_t         ct5PtCut20[82];   //[nPhotons]
   Float_t         ct4j20[82];   //[nPhotons]
   Float_t         ct4j10[82];   //[nPhotons]
   Float_t         ct4j15[82];   //[nPhotons]
   Float_t         ct4j[82];   //[nPhotons]
   Float_t         dr11[82];   //[nPhotons]
   Float_t         dr21[82];   //[nPhotons]
   Float_t         dr31[82];   //[nPhotons]
   Float_t         dr41[82];   //[nPhotons]
   Float_t         dr12[82];   //[nPhotons]
   Float_t         dr22[82];   //[nPhotons]
   Float_t         dr32[82];   //[nPhotons]
   Float_t         dr42[82];   //[nPhotons]
   Float_t         dr13[82];   //[nPhotons]
   Float_t         dr23[82];   //[nPhotons]
   Float_t         dr33[82];   //[nPhotons]
   Float_t         dr43[82];   //[nPhotons]
   Float_t         dr14[82];   //[nPhotons]
   Float_t         dr24[82];   //[nPhotons]
   Float_t         dr34[82];   //[nPhotons]
   Float_t         dr44[82];   //[nPhotons]
   Float_t         t11[82];   //[nPhotons]
   Float_t         t21[82];   //[nPhotons]
   Float_t         t31[82];   //[nPhotons]
   Float_t         t41[82];   //[nPhotons]
   Float_t         t12[82];   //[nPhotons]
   Float_t         t22[82];   //[nPhotons]
   Float_t         t32[82];   //[nPhotons]
   Float_t         t42[82];   //[nPhotons]
   Float_t         t13[82];   //[nPhotons]
   Float_t         t23[82];   //[nPhotons]
   Float_t         t33[82];   //[nPhotons]
   Float_t         t43[82];   //[nPhotons]
   Float_t         t14[82];   //[nPhotons]
   Float_t         t24[82];   //[nPhotons]
   Float_t         t34[82];   //[nPhotons]
   Float_t         t44[82];   //[nPhotons]
   Int_t           isGenMatched[82];   //[nPhotons]
   Int_t           genMatchedCollId[82];   //[nPhotons]
   Float_t         genMatchedPt[82];   //[nPhotons]
   Float_t         genMatchedEta[82];   //[nPhotons]
   Float_t         genMatchedPhi[82];   //[nPhotons]
   Int_t           genMomId[82];   //[nPhotons]
   Int_t           genGrandMomId[82];   //[nPhotons]
   Int_t           genNSiblings[82];   //[nPhotons]
   Float_t         genCalIsoDR03[82];   //[nPhotons]
   Float_t         genCalIsoDR04[82];   //[nPhotons]
   Float_t         genTrkIsoDR03[82];   //[nPhotons]
   Float_t         genTrkIsoDR04[82];   //[nPhotons]
   Int_t           nGp;
   Float_t         simVtxX;
   Float_t         simVtxY;
   Float_t         simVtxZ;
   Float_t         ptHat;
   Float_t         gpEt[180];   //[nGp]
   Float_t         gpEta[180];   //[nGp]
   Float_t         gpCalIsoDR04[180];   //[nGp]
   Float_t         gpCalIsoDR03[180];   //[nGp]
   Float_t         gpTrkIsoDR03[180];   //[nGp]
   Float_t         gpTrkIsoDR04[180];   //[nGp]
   Int_t           gpStatus[180];   //[nGp]
   Int_t           gpCollId[180];   //[nGp]
   Int_t           gpId[180];   //[nGp]
   Int_t           gpMomId[180];   //[nGp]

   // List of branches
   TBranch        *b_run;   //!
   TBranch        *b_event;   //!
   TBranch        *b_bunchCrossing;   //!
   TBranch        *b_luminosityBlock;   //!
   TBranch        *b_nPhotons;   //!
   TBranch        *b_pt;   //!
   TBranch        *b_energy;   //!
   TBranch        *b_rawEnergy;   //!
   TBranch        *b_eta;   //!
   TBranch        *b_phi;   //!
   TBranch        *b_r9;   //!
   TBranch        *b_isEB;   //!
   TBranch        *b_isEBGap;   //!
   TBranch        *b_isEEGap;   //!
   TBranch        *b_isEBEEGap;   //!
   TBranch        *b_isTransGap;   //!
   TBranch        *b_preshowerEnergy;   //!
   TBranch        *b_numOfPreshClusters;   //!
   TBranch        *b_ESRatio;   //!
   TBranch        *b_clustersSize;   //!
   TBranch        *b_scSize;   //!
   TBranch        *b_phiWidth;   //!
   TBranch        *b_etaWidth;   //!
   TBranch        *b_scEta;   //!
   TBranch        *b_scPhi;   //!
   TBranch        *b_sigmaEtaEta;   //!
   TBranch        *b_sigmaIetaIeta;   //!
   TBranch        *b_sigmaIphiIphi;   //!
   TBranch        *b_sieie50;   //!
   TBranch        *b_sieie45;   //!
   TBranch        *b_sieie47;   //!
   TBranch        *b_sieie42;   //!
   TBranch        *b_sieie39;   //!
   TBranch        *b_covPhiPhi;   //!
   TBranch        *b_covEtaPhi;   //!
   TBranch        *b_covEtaEta;   //!
   TBranch        *b_r1x5;   //!
   TBranch        *b_r2x5;   //!
   TBranch        *b_e1x5;   //!
   TBranch        *b_e2x5;   //!
   TBranch        *b_eMax;   //!
   TBranch        *b_e2nd;   //!
   TBranch        *b_e2x2;   //!
   TBranch        *b_e3x3;   //!
   TBranch        *b_e3x2;   //!
   TBranch        *b_e4x4;   //!
   TBranch        *b_e5x5;   //!
   TBranch        *b_e2overe8;   //!
   TBranch        *b_eRight;   //!
   TBranch        *b_eLeft;   //!
   TBranch        *b_eTop;   //!
   TBranch        *b_eBottom;   //!
   TBranch        *b_e2x5Right;   //!
   TBranch        *b_e2x5Left;   //!
   TBranch        *b_e2x5Top;   //!
   TBranch        *b_e2x5Bottom;   //!
   TBranch        *b_seedTime;   //!
   TBranch        *b_seedChi2;   //!
   TBranch        *b_seedOutOfTimeChi2;   //!
   TBranch        *b_seedRecoFlag;   //!
   TBranch        *b_seedSeverity;   //!
   TBranch        *b_swissCrx;   //!
   TBranch        *b_hadronicOverEm;   //!
   TBranch        *b_hadronicDepth1OverEm;   //!
   TBranch        *b_hadronicDepth2OverEm;   //!
   TBranch        *b_ecalRecHitSumEtConeDR04;   //!
   TBranch        *b_hcalTowerSumEtConeDR04;   //!
   TBranch        *b_hcalDepth1TowerSumEtConeDR04;   //!
   TBranch        *b_hcalDepth2TowerSumEtConeDR04;   //!
   TBranch        *b_trkSumPtHollowConeDR04;   //!
   TBranch        *b_trkSumPtSolidConeDR04;   //!
   TBranch        *b_ecalRecHitSumEtConeDR03;   //!
   TBranch        *b_hcalTowerSumEtConeDR03;   //!
   TBranch        *b_hcalDepth1TowerSumEtConeDR03;   //!
   TBranch        *b_hcalDepth2TowerSumEtConeDR03;   //!
   TBranch        *b_trkSumPtHollowConeDR03;   //!
   TBranch        *b_trkSumPtSolidConeDR03;   //!
   TBranch        *b_isEle;   //!
   TBranch        *b_hasPixelSeed;   //!
   TBranch        *b_detaEle;   //!
   TBranch        *b_dphiEle;   //!
   TBranch        *b_eleCharge;   //!
   TBranch        *b_eleEoverP;   //!
   TBranch        *b_c1;   //!
   TBranch        *b_c2;   //!
   TBranch        *b_c3;   //!
   TBranch        *b_c4;   //!
   TBranch        *b_c5;   //!
   TBranch        *b_r1;   //!
   TBranch        *b_r2;   //!
   TBranch        *b_r3;   //!
   TBranch        *b_r4;   //!
   TBranch        *b_r5;   //!
   TBranch        *b_t1;   //!
   TBranch        *b_t2;   //!
   TBranch        *b_t3;   //!
   TBranch        *b_t4;   //!
   TBranch        *b_t5;   //!
   TBranch        *b_t1PtCut;   //!
   TBranch        *b_t2PtCut;   //!
   TBranch        *b_t3PtCut;   //!
   TBranch        *b_t4PtCut;   //!
   TBranch        *b_t5PtCut;   //!
   TBranch        *b_cc1;   //!
   TBranch        *b_cc2;   //!
   TBranch        *b_cc3;   //!
   TBranch        *b_cc4;   //!
   TBranch        *b_cc4j;   //!
   TBranch        *b_cc5;   //!
   TBranch        *b_cc05;   //!
   TBranch        *b_cr1;   //!
   TBranch        *b_cr2;   //!
   TBranch        *b_cr3;   //!
   TBranch        *b_cr4;   //!
   TBranch        *b_cr5;   //!
   TBranch        *b_cr4j;   //!
   TBranch        *b_ct1;   //!
   TBranch        *b_ct2;   //!
   TBranch        *b_ct3;   //!
   TBranch        *b_ct4;   //!
   TBranch        *b_ct5;   //!
   TBranch        *b_ct1PtCut20;   //!
   TBranch        *b_ct2PtCut20;   //!
   TBranch        *b_ct3PtCut20;   //!
   TBranch        *b_ct4PtCut20;   //!
   TBranch        *b_ct5PtCut20;   //!
   TBranch        *b_ct4j20;   //!
   TBranch        *b_ct4j10;   //!
   TBranch        *b_ct4j15;   //!
   TBranch        *b_ct4j;   //!
   TBranch        *b_dr11;   //!
   TBranch        *b_dr21;   //!
   TBranch        *b_dr31;   //!
   TBranch        *b_dr41;   //!
   TBranch        *b_dr12;   //!
   TBranch        *b_dr22;   //!
   TBranch        *b_dr32;   //!
   TBranch        *b_dr42;   //!
   TBranch        *b_dr13;   //!
   TBranch        *b_dr23;   //!
   TBranch        *b_dr33;   //!
   TBranch        *b_dr43;   //!
   TBranch        *b_dr14;   //!
   TBranch        *b_dr24;   //!
   TBranch        *b_dr34;   //!
   TBranch        *b_dr44;   //!
   TBranch        *b_t11;   //!
   TBranch        *b_t21;   //!
   TBranch        *b_t31;   //!
   TBranch        *b_t41;   //!
   TBranch        *b_t12;   //!
   TBranch        *b_t22;   //!
   TBranch        *b_t32;   //!
   TBranch        *b_t42;   //!
   TBranch        *b_t13;   //!
   TBranch        *b_t23;   //!
   TBranch        *b_t33;   //!
   TBranch        *b_t43;   //!
   TBranch        *b_t14;   //!
   TBranch        *b_t24;   //!
   TBranch        *b_t34;   //!
   TBranch        *b_t44;   //!
   TBranch        *b_isGenMatched;   //!
   TBranch        *b_genMatchedCollId;   //!
   TBranch        *b_genMatchedPt;   //!
   TBranch        *b_genMatchedEta;   //!
   TBranch        *b_genMatchedPhi;   //!
   TBranch        *b_genMomId;   //!
   TBranch        *b_genGrandMomId;   //!
   TBranch        *b_genNSiblings;   //!
   TBranch        *b_genCalIsoDR03;   //!
   TBranch        *b_genCalIsoDR04;   //!
   TBranch        *b_genTrkIsoDR03;   //!
   TBranch        *b_genTrkIsoDR04;   //!
   TBranch        *b_nGp;   //!
   TBranch        *b_simVtxX;   //!
   TBranch        *b_simVtxY;   //!
   TBranch        *b_simVtxZ;   //!
   TBranch        *b_ptHat;   //!
   TBranch        *b_gpEt;   //!
   TBranch        *b_gpEta;   //!
   TBranch        *b_gpCalIsoDR04;   //!
   TBranch        *b_gpCalIsoDR03;   //!
   TBranch        *b_gpTrkIsoDR03;   //!
   TBranch        *b_gpTrkIsoDR04;   //!
   TBranch        *b_gpStatus;   //!
   TBranch        *b_gpCollId;   //!
   TBranch        *b_gpId;   //!
   TBranch        *b_gpMomId;   //!

};


void setupPhotonTree(TTree *t,Photons &tPhotons,bool doCheck = 0)
{
   // Set branch addresses and branch pointers
   t->SetBranchAddress("run", &tPhotons.run, &tPhotons.b_run);
   t->SetBranchAddress("event", &tPhotons.event, &tPhotons.b_event);
   t->SetBranchAddress("bunchCrossing", &tPhotons.bunchCrossing, &tPhotons.b_bunchCrossing);
   t->SetBranchAddress("luminosityBlock", &tPhotons.luminosityBlock, &tPhotons.b_luminosityBlock);
   t->SetBranchAddress("nPhotons", &tPhotons.nPhotons, &tPhotons.b_nPhotons);
   t->SetBranchAddress("pt", tPhotons.pt, &tPhotons.b_pt);
   t->SetBranchAddress("energy", tPhotons.energy, &tPhotons.b_energy);
   t->SetBranchAddress("rawEnergy", tPhotons.rawEnergy, &tPhotons.b_rawEnergy);
   t->SetBranchAddress("eta", tPhotons.eta, &tPhotons.b_eta);
   t->SetBranchAddress("phi", tPhotons.phi, &tPhotons.b_phi);
   t->SetBranchAddress("r9", tPhotons.r9, &tPhotons.b_r9);
   t->SetBranchAddress("isEB", tPhotons.isEB, &tPhotons.b_isEB);
   t->SetBranchAddress("isEBGap", tPhotons.isEBGap, &tPhotons.b_isEBGap);
   t->SetBranchAddress("isEEGap", tPhotons.isEEGap, &tPhotons.b_isEEGap);
   t->SetBranchAddress("isEBEEGap", tPhotons.isEBEEGap, &tPhotons.b_isEBEEGap);
   t->SetBranchAddress("isTransGap", tPhotons.isTransGap, &tPhotons.b_isTransGap);
   t->SetBranchAddress("preshowerEnergy", tPhotons.preshowerEnergy, &tPhotons.b_preshowerEnergy);
   t->SetBranchAddress("numOfPreshClusters", tPhotons.numOfPreshClusters, &tPhotons.b_numOfPreshClusters);
   t->SetBranchAddress("ESRatio", tPhotons.ESRatio, &tPhotons.b_ESRatio);
   t->SetBranchAddress("clustersSize", tPhotons.clustersSize, &tPhotons.b_clustersSize);
   t->SetBranchAddress("scSize", tPhotons.scSize, &tPhotons.b_scSize);
   t->SetBranchAddress("phiWidth", tPhotons.phiWidth, &tPhotons.b_phiWidth);
   t->SetBranchAddress("etaWidth", tPhotons.etaWidth, &tPhotons.b_etaWidth);
   t->SetBranchAddress("scEta", tPhotons.scEta, &tPhotons.b_scEta);
   t->SetBranchAddress("scPhi", tPhotons.scPhi, &tPhotons.b_scPhi);
   t->SetBranchAddress("sigmaEtaEta", tPhotons.sigmaEtaEta, &tPhotons.b_sigmaEtaEta);
   t->SetBranchAddress("sigmaIetaIeta", tPhotons.sigmaIetaIeta, &tPhotons.b_sigmaIetaIeta);
   t->SetBranchAddress("sigmaIphiIphi", tPhotons.sigmaIphiIphi, &tPhotons.b_sigmaIphiIphi);
   t->SetBranchAddress("sieie50", tPhotons.sieie50, &tPhotons.b_sieie50);
   t->SetBranchAddress("sieie45", tPhotons.sieie45, &tPhotons.b_sieie45);
   t->SetBranchAddress("sieie47", tPhotons.sieie47, &tPhotons.b_sieie47);
   t->SetBranchAddress("sieie42", tPhotons.sieie42, &tPhotons.b_sieie42);
   t->SetBranchAddress("sieie39", tPhotons.sieie39, &tPhotons.b_sieie39);
   t->SetBranchAddress("covPhiPhi", tPhotons.covPhiPhi, &tPhotons.b_covPhiPhi);
   t->SetBranchAddress("covEtaPhi", tPhotons.covEtaPhi, &tPhotons.b_covEtaPhi);
   t->SetBranchAddress("covEtaEta", tPhotons.covEtaEta, &tPhotons.b_covEtaEta);
   t->SetBranchAddress("r1x5", tPhotons.r1x5, &tPhotons.b_r1x5);
   t->SetBranchAddress("r2x5", tPhotons.r2x5, &tPhotons.b_r2x5);
   t->SetBranchAddress("e1x5", tPhotons.e1x5, &tPhotons.b_e1x5);
   t->SetBranchAddress("e2x5", tPhotons.e2x5, &tPhotons.b_e2x5);
   t->SetBranchAddress("eMax", tPhotons.eMax, &tPhotons.b_eMax);
   t->SetBranchAddress("e2nd", tPhotons.e2nd, &tPhotons.b_e2nd);
   t->SetBranchAddress("e2x2", tPhotons.e2x2, &tPhotons.b_e2x2);
   t->SetBranchAddress("e3x3", tPhotons.e3x3, &tPhotons.b_e3x3);
   t->SetBranchAddress("e3x2", tPhotons.e3x2, &tPhotons.b_e3x2);
   t->SetBranchAddress("e4x4", tPhotons.e4x4, &tPhotons.b_e4x4);
   t->SetBranchAddress("e5x5", tPhotons.e5x5, &tPhotons.b_e5x5);
   t->SetBranchAddress("e2overe8", tPhotons.e2overe8, &tPhotons.b_e2overe8);
   t->SetBranchAddress("eRight", tPhotons.eRight, &tPhotons.b_eRight);
   t->SetBranchAddress("eLeft", tPhotons.eLeft, &tPhotons.b_eLeft);
   t->SetBranchAddress("eTop", tPhotons.eTop, &tPhotons.b_eTop);
   t->SetBranchAddress("eBottom", tPhotons.eBottom, &tPhotons.b_eBottom);
   t->SetBranchAddress("e2x5Right", tPhotons.e2x5Right, &tPhotons.b_e2x5Right);
   t->SetBranchAddress("e2x5Left", tPhotons.e2x5Left, &tPhotons.b_e2x5Left);
   t->SetBranchAddress("e2x5Top", tPhotons.e2x5Top, &tPhotons.b_e2x5Top);
   t->SetBranchAddress("e2x5Bottom", tPhotons.e2x5Bottom, &tPhotons.b_e2x5Bottom);
   t->SetBranchAddress("seedTime", tPhotons.seedTime, &tPhotons.b_seedTime);
   t->SetBranchAddress("seedChi2", tPhotons.seedChi2, &tPhotons.b_seedChi2);
   t->SetBranchAddress("seedOutOfTimeChi2", tPhotons.seedOutOfTimeChi2, &tPhotons.b_seedOutOfTimeChi2);
   t->SetBranchAddress("seedRecoFlag", tPhotons.seedRecoFlag, &tPhotons.b_seedRecoFlag);
   t->SetBranchAddress("seedSeverity", tPhotons.seedSeverity, &tPhotons.b_seedSeverity);
   t->SetBranchAddress("swissCrx", tPhotons.swissCrx, &tPhotons.b_swissCrx);
   t->SetBranchAddress("hadronicOverEm", tPhotons.hadronicOverEm, &tPhotons.b_hadronicOverEm);
   t->SetBranchAddress("hadronicDepth1OverEm", tPhotons.hadronicDepth1OverEm, &tPhotons.b_hadronicDepth1OverEm);
   t->SetBranchAddress("hadronicDepth2OverEm", tPhotons.hadronicDepth2OverEm, &tPhotons.b_hadronicDepth2OverEm);
   t->SetBranchAddress("ecalRecHitSumEtConeDR04", tPhotons.ecalRecHitSumEtConeDR04, &tPhotons.b_ecalRecHitSumEtConeDR04);
   t->SetBranchAddress("hcalTowerSumEtConeDR04", tPhotons.hcalTowerSumEtConeDR04, &tPhotons.b_hcalTowerSumEtConeDR04);
   t->SetBranchAddress("hcalDepth1TowerSumEtConeDR04", tPhotons.hcalDepth1TowerSumEtConeDR04, &tPhotons.b_hcalDepth1TowerSumEtConeDR04);
   t->SetBranchAddress("hcalDepth2TowerSumEtConeDR04", tPhotons.hcalDepth2TowerSumEtConeDR04, &tPhotons.b_hcalDepth2TowerSumEtConeDR04);
   t->SetBranchAddress("trkSumPtHollowConeDR04", tPhotons.trkSumPtHollowConeDR04, &tPhotons.b_trkSumPtHollowConeDR04);
   t->SetBranchAddress("trkSumPtSolidConeDR04", tPhotons.trkSumPtSolidConeDR04, &tPhotons.b_trkSumPtSolidConeDR04);
   t->SetBranchAddress("ecalRecHitSumEtConeDR03", tPhotons.ecalRecHitSumEtConeDR03, &tPhotons.b_ecalRecHitSumEtConeDR03);
   t->SetBranchAddress("hcalTowerSumEtConeDR03", tPhotons.hcalTowerSumEtConeDR03, &tPhotons.b_hcalTowerSumEtConeDR03);
   t->SetBranchAddress("hcalDepth1TowerSumEtConeDR03", tPhotons.hcalDepth1TowerSumEtConeDR03, &tPhotons.b_hcalDepth1TowerSumEtConeDR03);
   t->SetBranchAddress("hcalDepth2TowerSumEtConeDR03", tPhotons.hcalDepth2TowerSumEtConeDR03, &tPhotons.b_hcalDepth2TowerSumEtConeDR03);
   t->SetBranchAddress("trkSumPtHollowConeDR03", tPhotons.trkSumPtHollowConeDR03, &tPhotons.b_trkSumPtHollowConeDR03);
   t->SetBranchAddress("trkSumPtSolidConeDR03", tPhotons.trkSumPtSolidConeDR03, &tPhotons.b_trkSumPtSolidConeDR03);
   t->SetBranchAddress("isEle", tPhotons.isEle, &tPhotons.b_isEle);
   t->SetBranchAddress("hasPixelSeed", tPhotons.hasPixelSeed, &tPhotons.b_hasPixelSeed);
   t->SetBranchAddress("detaEle", tPhotons.detaEle, &tPhotons.b_detaEle);
   t->SetBranchAddress("dphiEle", tPhotons.dphiEle, &tPhotons.b_dphiEle);
   t->SetBranchAddress("eleCharge", tPhotons.eleCharge, &tPhotons.b_eleCharge);
   t->SetBranchAddress("eleEoverP", tPhotons.eleEoverP, &tPhotons.b_eleEoverP);
   t->SetBranchAddress("c1", tPhotons.c1, &tPhotons.b_c1);
   t->SetBranchAddress("c2", tPhotons.c2, &tPhotons.b_c2);
   t->SetBranchAddress("c3", tPhotons.c3, &tPhotons.b_c3);
   t->SetBranchAddress("c4", tPhotons.c4, &tPhotons.b_c4);
   t->SetBranchAddress("c5", tPhotons.c5, &tPhotons.b_c5);
   t->SetBranchAddress("r1", tPhotons.r1, &tPhotons.b_r1);
   t->SetBranchAddress("r2", tPhotons.r2, &tPhotons.b_r2);
   t->SetBranchAddress("r3", tPhotons.r3, &tPhotons.b_r3);
   t->SetBranchAddress("r4", tPhotons.r4, &tPhotons.b_r4);
   t->SetBranchAddress("r5", tPhotons.r5, &tPhotons.b_r5);
   t->SetBranchAddress("t1", tPhotons.t1, &tPhotons.b_t1);
   t->SetBranchAddress("t2", tPhotons.t2, &tPhotons.b_t2);
   t->SetBranchAddress("t3", tPhotons.t3, &tPhotons.b_t3);
   t->SetBranchAddress("t4", tPhotons.t4, &tPhotons.b_t4);
   t->SetBranchAddress("t5", tPhotons.t5, &tPhotons.b_t5);
   t->SetBranchAddress("t1PtCut", tPhotons.t1PtCut, &tPhotons.b_t1PtCut);
   t->SetBranchAddress("t2PtCut", tPhotons.t2PtCut, &tPhotons.b_t2PtCut);
   t->SetBranchAddress("t3PtCut", tPhotons.t3PtCut, &tPhotons.b_t3PtCut);
   t->SetBranchAddress("t4PtCut", tPhotons.t4PtCut, &tPhotons.b_t4PtCut);
   t->SetBranchAddress("t5PtCut", tPhotons.t5PtCut, &tPhotons.b_t5PtCut);
   t->SetBranchAddress("cc1", tPhotons.cc1, &tPhotons.b_cc1);
   t->SetBranchAddress("cc2", tPhotons.cc2, &tPhotons.b_cc2);
   t->SetBranchAddress("cc3", tPhotons.cc3, &tPhotons.b_cc3);
   t->SetBranchAddress("cc4", tPhotons.cc4, &tPhotons.b_cc4);
   t->SetBranchAddress("cc4j", tPhotons.cc4j, &tPhotons.b_cc4j);
   t->SetBranchAddress("cc5", tPhotons.cc5, &tPhotons.b_cc5);
   t->SetBranchAddress("cc05", tPhotons.cc05, &tPhotons.b_cc05);
   t->SetBranchAddress("cr1", tPhotons.cr1, &tPhotons.b_cr1);
   t->SetBranchAddress("cr2", tPhotons.cr2, &tPhotons.b_cr2);
   t->SetBranchAddress("cr3", tPhotons.cr3, &tPhotons.b_cr3);
   t->SetBranchAddress("cr4", tPhotons.cr4, &tPhotons.b_cr4);
   t->SetBranchAddress("cr5", tPhotons.cr5, &tPhotons.b_cr5);
   t->SetBranchAddress("cr4j", tPhotons.cr4j, &tPhotons.b_cr4j);
   t->SetBranchAddress("ct1", tPhotons.ct1, &tPhotons.b_ct1);
   t->SetBranchAddress("ct2", tPhotons.ct2, &tPhotons.b_ct2);
   t->SetBranchAddress("ct3", tPhotons.ct3, &tPhotons.b_ct3);
   t->SetBranchAddress("ct4", tPhotons.ct4, &tPhotons.b_ct4);
   t->SetBranchAddress("ct5", tPhotons.ct5, &tPhotons.b_ct5);
   t->SetBranchAddress("ct1PtCut20", tPhotons.ct1PtCut20, &tPhotons.b_ct1PtCut20);
   t->SetBranchAddress("ct2PtCut20", tPhotons.ct2PtCut20, &tPhotons.b_ct2PtCut20);
   t->SetBranchAddress("ct3PtCut20", tPhotons.ct3PtCut20, &tPhotons.b_ct3PtCut20);
   t->SetBranchAddress("ct4PtCut20", tPhotons.ct4PtCut20, &tPhotons.b_ct4PtCut20);
   t->SetBranchAddress("ct5PtCut20", tPhotons.ct5PtCut20, &tPhotons.b_ct5PtCut20);
   t->SetBranchAddress("ct4j20", tPhotons.ct4j20, &tPhotons.b_ct4j20);
   t->SetBranchAddress("ct4j10", tPhotons.ct4j10, &tPhotons.b_ct4j10);
   t->SetBranchAddress("ct4j15", tPhotons.ct4j15, &tPhotons.b_ct4j15);
   t->SetBranchAddress("ct4j", tPhotons.ct4j, &tPhotons.b_ct4j);
   t->SetBranchAddress("dr11", tPhotons.dr11, &tPhotons.b_dr11);
   t->SetBranchAddress("dr21", tPhotons.dr21, &tPhotons.b_dr21);
   t->SetBranchAddress("dr31", tPhotons.dr31, &tPhotons.b_dr31);
   t->SetBranchAddress("dr41", tPhotons.dr41, &tPhotons.b_dr41);
   t->SetBranchAddress("dr12", tPhotons.dr12, &tPhotons.b_dr12);
   t->SetBranchAddress("dr22", tPhotons.dr22, &tPhotons.b_dr22);
   t->SetBranchAddress("dr32", tPhotons.dr32, &tPhotons.b_dr32);
   t->SetBranchAddress("dr42", tPhotons.dr42, &tPhotons.b_dr42);
   t->SetBranchAddress("dr13", tPhotons.dr13, &tPhotons.b_dr13);
   t->SetBranchAddress("dr23", tPhotons.dr23, &tPhotons.b_dr23);
   t->SetBranchAddress("dr33", tPhotons.dr33, &tPhotons.b_dr33);
   t->SetBranchAddress("dr43", tPhotons.dr43, &tPhotons.b_dr43);
   t->SetBranchAddress("dr14", tPhotons.dr14, &tPhotons.b_dr14);
   t->SetBranchAddress("dr24", tPhotons.dr24, &tPhotons.b_dr24);
   t->SetBranchAddress("dr34", tPhotons.dr34, &tPhotons.b_dr34);
   t->SetBranchAddress("dr44", tPhotons.dr44, &tPhotons.b_dr44);
   t->SetBranchAddress("t11", tPhotons.t11, &tPhotons.b_t11);
   t->SetBranchAddress("t21", tPhotons.t21, &tPhotons.b_t21);
   t->SetBranchAddress("t31", tPhotons.t31, &tPhotons.b_t31);
   t->SetBranchAddress("t41", tPhotons.t41, &tPhotons.b_t41);
   t->SetBranchAddress("t12", tPhotons.t12, &tPhotons.b_t12);
   t->SetBranchAddress("t22", tPhotons.t22, &tPhotons.b_t22);
   t->SetBranchAddress("t32", tPhotons.t32, &tPhotons.b_t32);
   t->SetBranchAddress("t42", tPhotons.t42, &tPhotons.b_t42);
   t->SetBranchAddress("t13", tPhotons.t13, &tPhotons.b_t13);
   t->SetBranchAddress("t23", tPhotons.t23, &tPhotons.b_t23);
   t->SetBranchAddress("t33", tPhotons.t33, &tPhotons.b_t33);
   t->SetBranchAddress("t43", tPhotons.t43, &tPhotons.b_t43);
   t->SetBranchAddress("t14", tPhotons.t14, &tPhotons.b_t14);
   t->SetBranchAddress("t24", tPhotons.t24, &tPhotons.b_t24);
   t->SetBranchAddress("t34", tPhotons.t34, &tPhotons.b_t34);
   t->SetBranchAddress("t44", tPhotons.t44, &tPhotons.b_t44);
   t->SetBranchAddress("isGenMatched", tPhotons.isGenMatched, &tPhotons.b_isGenMatched);
   t->SetBranchAddress("genMatchedCollId", tPhotons.genMatchedCollId, &tPhotons.b_genMatchedCollId);
   t->SetBranchAddress("genMatchedPt", tPhotons.genMatchedPt, &tPhotons.b_genMatchedPt);
   t->SetBranchAddress("genMatchedEta", tPhotons.genMatchedEta, &tPhotons.b_genMatchedEta);
   t->SetBranchAddress("genMatchedPhi", tPhotons.genMatchedPhi, &tPhotons.b_genMatchedPhi);
   t->SetBranchAddress("genMomId", tPhotons.genMomId, &tPhotons.b_genMomId);
   t->SetBranchAddress("genGrandMomId", tPhotons.genGrandMomId, &tPhotons.b_genGrandMomId);
   t->SetBranchAddress("genNSiblings", tPhotons.genNSiblings, &tPhotons.b_genNSiblings);
   t->SetBranchAddress("genCalIsoDR03", tPhotons.genCalIsoDR03, &tPhotons.b_genCalIsoDR03);
   t->SetBranchAddress("genCalIsoDR04", tPhotons.genCalIsoDR04, &tPhotons.b_genCalIsoDR04);
   t->SetBranchAddress("genTrkIsoDR03", tPhotons.genTrkIsoDR03, &tPhotons.b_genTrkIsoDR03);
   t->SetBranchAddress("genTrkIsoDR04", tPhotons.genTrkIsoDR04, &tPhotons.b_genTrkIsoDR04);
   t->SetBranchAddress("nGp", &tPhotons.nGp, &tPhotons.b_nGp);
   t->SetBranchAddress("simVtxX", &tPhotons.simVtxX, &tPhotons.b_simVtxX);
   t->SetBranchAddress("simVtxY", &tPhotons.simVtxY, &tPhotons.b_simVtxY);
   t->SetBranchAddress("simVtxZ", &tPhotons.simVtxZ, &tPhotons.b_simVtxZ);
   t->SetBranchAddress("ptHat", &tPhotons.ptHat, &tPhotons.b_ptHat);
   t->SetBranchAddress("gpEt", tPhotons.gpEt, &tPhotons.b_gpEt);
   t->SetBranchAddress("gpEta", tPhotons.gpEta, &tPhotons.b_gpEta);
   t->SetBranchAddress("gpCalIsoDR04", tPhotons.gpCalIsoDR04, &tPhotons.b_gpCalIsoDR04);
   t->SetBranchAddress("gpCalIsoDR03", tPhotons.gpCalIsoDR03, &tPhotons.b_gpCalIsoDR03);
   t->SetBranchAddress("gpTrkIsoDR03", tPhotons.gpTrkIsoDR03, &tPhotons.b_gpTrkIsoDR03);
   t->SetBranchAddress("gpTrkIsoDR04", tPhotons.gpTrkIsoDR04, &tPhotons.b_gpTrkIsoDR04);
   t->SetBranchAddress("gpStatus", tPhotons.gpStatus, &tPhotons.b_gpStatus);
   t->SetBranchAddress("gpCollId", tPhotons.gpCollId, &tPhotons.b_gpCollId);
   t->SetBranchAddress("gpId", tPhotons.gpId, &tPhotons.b_gpId);
   t->SetBranchAddress("gpMomId", tPhotons.gpMomId, &tPhotons.b_gpMomId);
   if (doCheck) {
      if (t->GetMaximum("nPhotons")>82) cout <<"FATAL ERROR: Arrary size of nPhotons too small!!!  "<<t->GetMaximum("nPhotons")<<endl;
      if (t->GetMaximum("nGp")>180) cout <<"FATAL ERROR: Arrary size of nGp too small!!!  "<<t->GetMaximum("nGp")<<endl;
   }
}

